tomcat:
  image:
    tomcat: metricstreaminc/tech-doc:tomcat-k8s-2.0
  ports:
    port: 443
    targetPort: 8443
    nodePort: 30001
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true   
  resources: 
    requests: 
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 3Gi
      cpu: 1
  hostPath: "/home/kairos/grv/techdoc/tomcat/data/"
postgres:
  image:
    postgres: postgres:11.4
    postgres_init: metricstreaminc/tech-doc:postgres-init-1.0
  ports:
    port: 5432
  resources:
    requests:
      memory: 3Gi
      cpu: 500m
    limits:
      memory: 5Gi
      cpu: 1
  hostPath: "/home/kairos/grv/techdoc/postgres/data/"
