apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
  - port: {{ .Values.postgres.ports.port }}
    name: postgres
  clusterIP: None
  selector:
    db: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  selector:
    matchLabels:
      db: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
      - image: {{ .Values.postgres.image.postgres }}
        name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        ports:
        - containerPort: {{ .Values.postgres.ports.port }}
          name: postgres-port
        volumeMounts:
#        - name: postgres-persistent-volume
#          mountPath: /var/lib/postgresql/data
        - name: postgres-init-persistent-volume
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: {{ .Values.postgres.resources.requests.memory }}
            cpu: {{ .Values.postgres.resources.requests.cpu }}
          limits:
            memory: {{ .Values.postgres.resources.limits.memory }}
            cpu: {{ .Values.postgres.resources.limits.cpu }}
      volumes:
 #     - name: postgres-persistent-volume
 #       persistentVolumeClaim:
 #         claimName: postgres-persistent-volume-claim
      - name: postgres-init-persistent-volume
        persistentVolumeClaim:
          claimName: postgres-init-persistent-volume-claim
      initContainers:
      - name: postgres-data-init
        image: {{ .Values.postgres.image.postgres_init }} 
        volumeMounts:
        - name: postgres-init-persistent-volume
          mountPath: /docker-entrypoint-initdb.d
