apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  ports:
    - name: tomcat-service-port
      protocol: TCP
      port: {{ .Values.tomcat.ports.port }}
      targetPort: {{ .Values.tomcat.ports.targetPort }}
      nodePort: {{ .Values.tomcat.ports.nodePort }}
  selector:
    app: tomcat
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: {{ .Values.tomcat.image.tomcat }}
        name: tomcat
        securityContext:
          fsGroup: 1000
        env:
        - name: TZ
          value: Asia/Kolkata 
        ports:
        - containerPort: {{ .Values.tomcat.ports.targetPort }}
          name: tomcat-port
        volumeMounts:
        - name: tomcat-persistent-volume
          mountPath: /opt/reports
        securityContext:
          runAsUser: {{ .Values.tomcat.securityContext.runAsUser }}
          runAsGroup: {{ .Values.tomcat.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.tomcat.securityContext.runAsNonRoot }}
        resources:
          requests:
            memory: {{ .Values.tomcat.resources.requests.memory }}
            cpu: {{ .Values.tomcat.resources.requests.cpu }}
          limits:
            memory: {{ .Values.tomcat.resources.limits.memory }}
            cpu: {{ .Values.tomcat.resources.limits.cpu }}
      volumes:
      - name: tomcat-persistent-volume
        persistentVolumeClaim:
          claimName: tomcat-persistent-volume-claim
      initContainers:
      - name: tomcat-init
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /opt/reports"]
        volumeMounts:
        - name: tomcat-persistent-volume
          mountPath: /opt/reports
