apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  ports:
    - name: tomcat-service-port
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30001
  selector:
    app: tomcat
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: {{ .Values.image.TOMCAT }}
        name: tomcat
        ports:
        - containerPort: 8443
          name: postgres-port
        volumeMounts:
        - name: tomcat-persistent-volume
          mountPath: /opt/reports
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      volumes:
      - name: tomcat-persistent-volume
        persistentVolumeClaim:
          claimName: tomcat-persistent-volume-claim
