apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  labels:
    type: local-postgres
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.resources.limits.memory }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
  labels:
    type: local-postgres
    db: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.resources.requests.memory }}

