apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kairos/grv/techdoc/tomcat/data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-persistent-volume-claim
  labels:
    type: local
    app: tomcat
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

