apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-persistent-volume
  labels:
    type: local-tomcat
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.tomcat.resources.limits.memory }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.tomcat.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-persistent-volume-claim
  labels:
    type: local-tomcat
    app: tomcat
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tomcat.resources.requests.memory }}

